<?php

/**
 * Implements hook_libraries_info()
 * @return string
 */

function mautic_api_library_libraries_info() {

  $libraries['mautic'] = array(
    'name' => 'Mautic',
    'vendor url' => 'https://github.com/mautic/api-library',
    'download url' => 'https://github.com/mautic/api-library',
    'version' => '1.0',
    'xautoload' => function($adapter) {
    /** @var \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter */
          // Scan sites/all/libraries/mautic/composer.json to look for
          // autoload information.
          $adapter->composerJson('composer.json');
        },
  );

  return $libraries;
}
